#Author: tbui@tibco.com
@DMDV110
Feature: SaveGraph
  As a user, I want to save, load and share graph.

  Background: 
    Given I login to EBX succesfully

  Scenario Outline: Check that save graph with graph name.
  Given I access dataspace "Master Data - Reference>DMDV1.1.0"
  Given I access dataset "US09"
  And user views data model graph
  When user saves graph as the name "<graphName>" and description "<description>" and Owner "<owner>" and sharWith "<shareWith>"
  Given open saved graph page
  Then verify saved graph with "<graphName>" and user profile "<username>"
  Then delete saved graph with "<graphName>" and user profile "<username>"
  Then verify saved graph with "<graphName>" and user "<user>"
  Then delete saved graph with "<graphName>" and user "<user>"
  
  Examples:
  | graphName                                                                                                                                                                                        | description                                                                                                                                                                                      | owner               | shareWith           | username | user          |
  | Graph 1                                                                                                                                                                                          |                                                                                                                                                                                                  |                     |                     | admin    |               |
  | !@$%^&*()_+{}:<>?                                                                                                                                                                                |                                                                                                                                                                                                  |                     |                     | admin    |               |
  | <body></body>                                                                                                                                                                                    |                                                                                                                                                                                                  |                     |                     | admin    |               |
  | We should add a new group ‘Label’ in the ‘Table configuration’ table, after the Color field. This group would contain fields similar to the ones used to define a label for a table in the day1. |                                                                                                                                                                                                  |                     |                     | admin    |               |
  |||||||
  | US09-11                                                                                                                                                                                          | Graph 1                                                                                                                                                                                          |                     |                     | admin    |               |
  | US09-12                                                                                                                                                                                          | !@$%^&*()_+{}:<>?                                                                                                                                                                                |                     |                     | admin    |               |
  | US09-14                                                                                                                                                                                          | <body></body>                                                                                                                                                                                    |                     |                     | admin    |               |
  | US09-15                                                                                                                                                                                          | We should add a new group ‘Label’ in the ‘Table configuration’ table, after the Color field. This group would contain fields similar to the ones used to define a label for a table in the day1. |                     |                     | admin    |               |
  | US09-16                                                                                                                                                                                          |                                                                                                                                                                                                  |                     |                     | admin    |               |
  | Us09-21                                                                                                                                                                                          | Us09-21                                                                                                                                                                                          |                     |                     | admin    |               |
  | !@$%^&*()_+{}:<>?                                                                                                                                                                                | !@$%^&*()_+{}:<>?                                                                                                                                                                                |                     |                     | admin    |               |
  | <body></body>                                                                                                                                                                                    | <body></body>                                                                                                                                                                                    |                     |                     | admin    |               |
  | We should add a new group ‘Label’ in the ‘Table configuration’ table, after the Color field. This group would contain fields similar to the ones used to define a label for a table in the day1. | We should add a new group ‘Label’ in the ‘Table configuration’ table, after the Color field. This group would contain fields similar to the ones used to define a label for a table in the day1. |                     |                     | admin    |               |
  | US09-36                                                           .                                                                                                                               |                                                                                                                                                                                                  |                     |                     | admin    |               |
  | US09-38                                                                                                                                                                                          |                                                                                                                                                                                                  |                     | admin admin (admin) | admin    |               |
  | US09-39                                                                                                                                                                                          |                                                                                                                                                                                                  |                     | Reg 1 (Reg1)        | admin    |               |
  | US09-40                                                                                                                                                                                          |                                                                                                                                                                                                  |                     | [all profiles]      | admin    |               |
  | US09-41                                                                                                                                                                                          |                                                                                                                                                                                                  |                     | test 2 (test2)      | admin    |               |
  | US09-43                                                                                                                                                                                          |                                                                                                                                                                                                  |                     | admin admin (admin) | admin    |               |
  | US09-31                                                                                                                                                                                          |                                                                                                                                                                                                  | [administrator]     |                     |          | administrator |
  | US09-32                                                                                                                                                                                          |                                                                                                                                                                                                  | Reg 1 (Reg1)        |                     | Reg1     |               |
  | US09-33                                                                                                                                                                                          |                                                                                                                                                                                                  | [all profiles]      |                     |          | everyone      |
  | US09-34                                                                                                                                                                                          |                                                                                                                                                                                                  | test 2 (test2)      |                     | test2    |               |
  | US09-35                                                                                                                                                                                          |                                                                                                                                                                                                  | admin admin (admin) |                     | admin    |               |
  
  Scenario Outline: Check that load saved graph
  Given I access dataspace "Master Data - Reference>DMDV1.1.0"
  Given I access dataset "US09"
  And user views data model graph
  When user loads new graph has the name "US09-26"
  Then the graph should be displayed
  When user saves graph as the name "<graphName>" and description "<description>" and Owner "<owner>" and sharWith "<shareWith>"
  
  Examples:
  | graphName | description | owner | shareWith |
  | US09-26   |             |       |           |


